### ISSUE TITLE
.../binding.node, 1): no suitable image found.

### ISSUE THREAD

**Issue by n1kk** [vshaxe/hashlink-debugger#27]
Trying to follow getting started guide on heaps.io

.hl file is being compiled fine, but when I run debugger i get this error in extensions output:
```
/Users/n1kk/.vscode/extensions/haxefoundation.haxe-hl-0.4.4/node_modules/bindings/bindings.js:98
  if( lasterr ) throw lasterr;
                ^
Error: dlopen(/Users/n1kk/.vscode/extensions/haxefoundation.haxe-hl-0.4.4/node_modules/ref/build/Release/binding.node, 1): no suitable image found.  Did find:
	/Users/n1kk/.vscode/extensions/haxefoundation.haxe-hl-0.4.4/node_modules/ref/build/Release/binding.node: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
	/Users/n1kk/.vscode/extensions/haxefoundation.haxe-hl-0.4.4/node_modules/ref/build/Release/binding.node: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at bindings (/Users/n1kk/.vscode/extensions/haxefoundation.haxe-hl-0.4.4/node_modules/bindings/bindings.js:85:44)
    at Object.<anonymous> (/Users/n1kk/.vscode/extensions/haxefoundation.haxe-hl-0.4.4/node_modules/ref/lib/ref.js:5:47)
```
VSCode Version 1.28.2 (1.28.2), MacOS 10.14
node v10.12.0 (npm v6.4.1)

Tried reinstalling clean VSCode and just installed Haxe Extension Pack 1.3.0, didn't help.

Any ideas what is causing this?

**Comment by Gama11** [comment]
According to the readme, Mac currently isn't supported:

>### OSX version
>Both Windows and Linux are supported. We will soon work on OSX version using Mach tasks debugging API.

**Comment by n1kk** [comment]
Oh, guess I should've paid more attention.
I naively assumed that if it is available to install it should be supported.
